hardy_blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('hardy_blogs.urls', namespace='hardy_blogs')),
]

hardy_blogs/urls.py
"""定义hardy_blogs的URL模式"""

from django.conf.urls import url
from .views import ArticleListView, ArticleDetailView, ArticlePublishView, ArticleEditView

urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='blog_index'),
    url(r'^article/publish$', ArticlePublishView.as_view(), name='article_publish'),
    url(r'^article/(?P<title>\w+\.?\w+)$', ArticleDetailView.as_view(), name='article_detail'),
    url(r'^article/(?P<title>\w+\.?\w+)/edit$', ArticleEditView.as_view(), name='article_edit'),
]

hardy_blogs/models.py
from django.db import models

class Article(models.Model):
    url = models.URLField()
    title = models.CharField(max_length=50)
    title_zh = models.CharField(max_length=50)
    author = models.CharField(max_length=30)
    content_md = models.TextField()
    content_html = models.TextField()
    tags = models.CharField(max_length=30)
    views = models.IntegerField()
    created = models.DateTimeField()
    updated = models.DateTimeField()

hardy_blogs/forms.py
#!/usr/bin/env python3
# coding=utf-8
import datetime
import re
import markdown

from django import forms

from hardy_blogs.models import Article


class ArticlePublishForm(forms.Form):
    title = forms.CharField(
        label=u'文章标题',
        max_length=50,
        widget=forms.TextInput(attrs={'class': '', 'placeholder': u'记得在标题末尾添加".html"'}),
    )

    content = forms.CharField(
        label=u'内容',
        min_length=10,
        widget=forms.Textarea(),
    )

    tags = forms.CharField(
        label=u'标签',
        max_length=30,
        widget=forms.TextInput(attrs={'class': '', 'placeholder': u'文章标签，以空格进行分割'}),
    )

    def save(self, username, article=None):
        cd = self.cleaned_data
        title = cd['title']
        title_zh = title
        now = datetime.datetime.now()
        content_md = cd['content']
        # content_html = markdown.markdown(cd['content'])
        content_html = markdown.markdown(cd['content'], extensions=['markdown.extensions.extra', 'markdown.extensions.codehilite'])
        re_title = '<h\d>(.+)</h\d>'
        data = content_html.split('\n')
        for line in data:
            title_info = re.findall(re_title, line)
            if title_info:
                title_zh = title_info[0]
                break
        url = '/article/%s' % (title)
        tags = cd['tags']
        if article:
            article.url = url
            article.title = title
            article.title_zh = article
            article.content_md = content_md
            article.content_html = content_html
            article.tags = tags
            article.updated = now
        else:
            article = Article(
                url=url,
                title=title,
                title_zh=title_zh,
                author=username,
                content_md=content_md,
                content_html=content_html,
                tags=tags,
                views=0,
                created=now,
                updated=now)
        article.save()

hardy_blogs/views.py
from django.core.urlresolvers import reverse
from django.contrib.admin.views.decorators import staff_member_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import F
from django.http import Http404
from django.views.generic.edit import FormView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from hardy_blogs.models import Article
from hardy_blogs.forms import ArticlePublishForm

class AdminRequiredMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(AdminRequiredMixin, cls).as_view(**initkwargs)
        return staff_member_required(view)

class ArticleListView(ListView):
    template_name = 'blog_index.html'

    def get_queryset(self, **kwargs):
        object_list = Article.objects.all().order_by(F('created').desc())[:100]
        paginator = Paginator(object_list, 10)
        page = self.request.GET.get('page')
        try:
            object_list = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            object_list = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            object_list = paginator.page(paginator.num_pages)
        return object_list

class ArticlePublishView(AdminRequiredMixin, FormView):
    template_name = 'article_publish.html'
    form_class = ArticlePublishForm

    def form_valid(self, form):
        form.save(self.request.user.username)
        return super(ArticlePublishView, self).form_valid(form)

    def get_success_url(self):
        title = self.request.POST.get('title')
        success_url = reverse('article_detail', args=(title,))
        return success_url

class ArticleDetailView(DetailView):
    template_name = 'article_detail.html'

    def get_object(self, **kwargs):
        title = self.kwargs.get('title')
        try:
            article = Article.objects.get(title=title)
            article.views += 1
            article.save()
            article.tags = article.tags.split()
        except Article.DoesNotExist:
            raise Http404("Article does not exist")
        return article

class ArticleEditView(AdminRequiredMixin, FormView):
    template_name = 'article_publish.html'
    form_class = ArticlePublishForm
    article = None

    def get_initial(self, **kwargs):
        title = self.kwargs.get('title')
        try:
            self.article = Article.objects.get(title=title)
            initial = {
                'title': title,
                'content': self.article.content_md,
                'tags': self.article.tags,
            }
            return initial
        except Article.DoesNotExist:
            raise Http404("Article does not exist")

    def form_valid(self, form):
        form.save(self.request, self.article)
        return super(ArticleEditView, self).form_valid(form)

    def get_success_url(self):
        title = self.request.POST.get('title')
        success_url = reverse('article_detail', args=(title,))
        return success_url

hardy_blogs/templates/article_detail.html
{% extends 'blog_base.html' %}

{% block title %}
<title>{{ object.title_zh }} | hardy's blog</title>
{% endblock %}

{% block content %}
<div class="container">
  <div class="article">
    <div class="article-info">
      <p class="pull-right" title="发表日期"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>{{ object.created|date:"Y/n/j G:i" }}</p>
      <p class="pull-right author" title="作者"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>{{ object.author }}</p>
      <p title="阅读次数"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>&times;{{ object.views }}</p>
    </div>
    <div class="article-tags">
      <span class="label label-primary"><span class="glyphicon glyphicon-tags" aria-hidden="true"></span> 文章标签：</span>
      {% for tag in object.tags %}
      <span class="label label-info"><span class="glyphicon glyphicon-tag" aria-hidden="true"></span> {{ tag }}</span>
      {% endfor %}
    </div>
    <div class="article-content">
      {% autoescape off %}
      {{ object.content_html }}
      {% endautoescape %}
      <p class="updated">---------- 全文完（最近更新于 {{ object.updated|date:"Y/n/j G:i" }}） ----------</p>
    </div>
  </div>
</div>
{% endblock %}

hardy_blogs/templates/article_publish.html
{% extends 'blog_base.html' %}

{% block extra_head %}
<link rel="stylesheet" href="//cdn.jsdelivr.net/editor/0.1.0/editor.css">
<script src="//cdn.jsdelivr.net/editor/0.1.0/editor.js"></script>
<script src="//cdn.jsdelivr.net/editor/0.1.0/marked.js"></script>
{% endblock %}

{% block content %}
<div class="container">
  <div class="publish center-block">
    <form novalidate action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
      <button type="submit" class="btn btn-primary">发 布</button>
    </form>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
  var editor = new Editor();
  editor.render();
</script>
{% endblock %}

hardy_blogs/templates/blog_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'img/logo.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/emacs.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <script src="http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    {% block title %}{% endblock %}
    {% block extra_head %}{% endblock %}
  </head>
  <body>
    {% block nav %}
      {% include "blog_nav.html" %}
    {% endblock %}

    {% block content %}{% endblock %}

    {% block footer %}{% endblock %}

    {% block scripts %}{% endblock %}
  </body>
</html>

hardy_blogs/templates/blog_index.html
{% extends 'blog_base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      {% for o in object_list %}
      <div class="article-item">
        <div class="article-info">
          <h3>{{ o.title_zh }}</h3>
          <p>阅读次数：{{ o.views }}，作者：{{ o.author }}，发布时间：{{ o.created|date:"Y/n/j" }}，文章标签：{{ o.tags }}</p>
        </div>
        <div class="summary">
          {% autoescape off %}
          <a href="{% url 'hardy_blogs:article_detail' o.title %}">{{ o.content_html|truncatechars_html:100 }}</a>
          {% endautoescape %}
        </div>
      </div>
      {% endfor %}
      <nav>
        <ul class="pager">
          <li class="current">{{ object_list.number  }} / {{ object_list.paginator.num_pages  }}</li>
          {% if object_list.has_previous %}
          <li class="previous"><a href="?page={{ object_list.previous_page_number  }}"><span aria-hidden="true">&larr;</span> 上一页</a></li>
          {% else %}
          <li class="previous disabled"><a href=""><span aria-hidden="true">&larr;</span> 上一页</a></li>
          {% endif %}
          {% if object_list.has_next %}
          <li class="next"><a href="?page={{ object_list.next_page_number  }}">下一页 <span aria-hidden="true">&rarr;</span></a></li>
          {% else %}
          <li class="next disabled"><a href="">下一页 <span aria-hidden="true">&rarr;</span></a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>
{% endblock %}

hardy_blogs/templates/blog_nav.html
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="{% url 'hardy_blogs:blog_index' %}" class="navbar-brand">hardy's blog</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse bs-navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'hardy_blogs:article_publish' %}">Link</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
        <a href="" title="个人信息"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ user.username }}</a>
        </li>
        {% else %}
        {% endif %}
      </ul>
    </div>
  </div>
</nav>